# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chris Phillips' Blog
email: chris.phillips@uk.ibm.com
description: API, Integration and Governance SME and Enthusiast, My opinions are very much mine
#An blog on APIs and other interesting Technology
baseurl: "/" # the subpath of your site, e.g. /blog
url: ""

highlighter: rouge
excerpt_separator: <!--more-->


twitter_username: cminion
github_username:  ChrisPhillips-cminion

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 10
paginate_path: "/page:num/"

future: false
site:
  disqus:
    shortname: chrisphillips-blog
disqus:
  shortname: chrisphillips-blog

minima:
  social_links:
    twitter: cminion
    github: ChrisPhillips-cminion
    linkedin: chrisjphillips
